### ISSUE TITLE
MKS Robin Nano V3 does not work with MKS H43 display

### ISSUE THREAD

**Issue by spammchik** [makerbase-mks/Marlin-V2.X-MKS-H43#10]
For **Robin Nano V3** I am using the firmware https://github.com/makerbase-mks/Marlin-V2.X-MKS-H43
I compile like this:
**platformio.ini**
default_envs = mks_robin_nano_v3
**Configuration.h**
#define SERIAL_PORT 3
#define BAUDRATE 115000
#define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3 
#define DGUS_LCD_UI_MKS
#define USE_MKS_GREEN_UI
**Configuration_adv.h**
#define LCD_SERIAL_PORT 1
#define LCD_BAUDRATE 115200

For **MKS H43 display** I am using the firmware https://github.com/makerbase-mks/MKS-H43-firmware/tree/main/H43_Firmware_1.31

However, when the MKS Robin Nano V3 is turned on, only the green "MKS Makerbase" splash screen appears on the H43 display. Further on the display nothing happens, there are no printer control buttons.
What should I do to get the display to work?

![IMG_20210322_163434](https://user-images.githubusercontent.com/9574372/111969705-1a8a6a00-8b2d-11eb-8ab1-e6080310bf99.jpg)

**platformio.ini**
default_envs = mks_robin_nano_v3_usb_flash_drive
Doesn't help. The display does not show anything other than the "MKS Makerbase" splash screen.

**Comment by spammchik** [comment]
**platformio.ini**
default_envs = mks_robin_nano_v3_usb_flash_drive
Doesn't help. The display does not show anything other than the "MKS Makerbase" splash screen.

**Comment by xNeurosynapticx** [comment]
https://drive.google.com/file/d/14Wm9G2I8A0vBd0500yb8ocpsc2SeU5xx/view?usp=sharing

This configuration works for me.

I have a Robin nano v3, mks ts32v2.0, wifi module, mksh43v1.0, mksservo57bv2.0.

I recommend using:.

https://github.com/makerbase-mks/MKS-H43-firmware/tree/main/H43_Firmware_1.30

I only managed to use H43 full and TS35 without wifi and the ability to move in the display.

**Comment by spammchik** [comment]
> https://drive.google.com/file/d/14Wm9G2I8A0vBd0500yb8ocpsc2SeU5xx/view?usp=sharing
> This configuration works for me.
Cool! The H43 display really worked.
But still something is wrong.
1) The temperature of the table and nozzle is not displayed in the RepeaterHost, it shows only 0.
2) USB does not work - does not show the file list on the P43 display

**Comment by xNeurosynapticx** [comment]
> > https://drive.google.com/file/d/14Wm9G2I8A0vBd0500yb8ocpsc2SeU5xx/view?usp=sharing
> > This configuration works for me.
> > I recommend using:.
> > https://github.com/makerbase-mks/MKS-H43-firmware/tree/main/H43_Firmware_1.30
> 
> Cool! The H43 display really worked.
> But still something is wrong.
> 
> 1. The temperature of the table and nozzle is not displayed in the RepetierHost, it shows only 0. (port BAUDRATE is 115200)
> 2. USB does not work - does not show the file list on the H43 display
.
> 1. on the H43 screen it also shows 0? 

Yes. in my log it shows this:
11:36:00.266 : UpdateScreenVPData Screen: 1 VP: 8192 VP: 8196 VP: 8256 VP: 8260 VP: 9984 VP: 0 UpdateScreenVPData done
11:36:00.268 : (3) # 130 79 75 # >
11:36:00.268 : (3) # 130 79 75 # >
11:36:00.269 : (3) # 130 79 75 # >
11:36:00.270 : (3) # 130 79 75 # >
11:36:00.271 : (3) # 130 79 75 # >
11:36:00.277 : T: / B: / @:0 B@:0

I am still trying to figure out how to enable H43 in this firmware:
everything works perfect. WIFI, TS35, USB connection, MiniSD, MKS Servo, except H43.

[Mks-Robin-Nano-Marlin2.0-Firmware-master.zip](https://github.com/makerbase-mks/Marlin-V2.X-MKS-H43/files/6212531/Mks-Robin-Nano-Marlin2.0-Firmware-master.zip)

> 2.do you mean the usb port on the board or the usb connection between the board and the computer?
the H43 display only shows files stored in the miniSD.

**Comment by xNeurosynapticx** [comment]
[Robin_nano_v3.zip](https://github.com/makerbase-mks/Marlin-V2.X-MKS-H43/files/6213702/Robin_nano_v3.zip)

https://drive.google.com/file/d/1-xtct92XxQM_H869CIb3FjITY8hm4ljc/view?usp=sharing

FULLY functional firmware for Robin nano v3.0 + H43 fw 1.30 + TS32 + WIFI +Serial comunication

**Comment by spammchik** [comment]
> https://drive.google.com/file/d/1-xtct92XxQM_H869CIb3FjITY8hm4ljc/view?usp=sharing
> FULLY functional firmware for Robin nano v3.0 + H43 fw 1.30 + TS32 + WIFI +Serial comunication

Cool man, it works!
You are doing more than the manufacturers of these electronics to improve the firmware.
Now the firmware shows the temperature in the RepetierHost!
Display H43 is working.
However, I could not enable USB support,
#define USB_FLASH_DRIVE_SUPPORT - doesn't work. The firmware could not compile, gave an error:
Marlin\src\lcd\extui\lib\mks_ui\tft_lvgl_configuration.cpp: In function 'void tft_lvgl_init()':
Marlin\src\lcd\extui\lib\mks_ui\tft_lvgl_configuration.cpp:134:15: error: 'USB_POWER_CONTROL_PIN' was not declared in this scope
134 |     OUT_WRITE(USB_POWER_CONTROL_PIN, HIGH);

And when I did this:
[platformio]
**default_envs = mks_robin_nano_v3_usb_flash_drive_msc**
the firmware could not compile, gave an error.

At the moment, I have never seen USB support working on this board.

It is very necessary for the new H43 display to work, for the RepetierHost to show the temperature, and for USB support to work for printing from a flash drive.
However, this problem has not yet been solved by the electronics manufacturer itself, all the firmware is bad. Something is definitely not working.

**Comment by reQu1em00** [comment]
For a nano v3:

Configuration.h
#define SERIAL_PORT -1
#define BAUDRATE 250000

Configuration_adv.h
#define LCD_SERIAL_PORT 3
#define LCD_BAUDRATE 115200

**Comment by spammchik** [comment]
We continue to discuss here:
https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware/issues/216
