### ISSUE TITLE
"PAUSE_BEFORE_DEPLOY_STOW" function is not supported

### ISSUE THREAD

**Issue by Foxies-CSTL** [makerbase-mks/Marlin-V2.X-MKS-H43#12]
### Description

The "PAUSE_BEFORE_DEPLOY_STOW" function is not supported by the H43 interface and fails to compile.
This function is necessary for people who use removable probes like Delta printers.

At compile time, I have a failure on the feedback screen because the status asks for a Marlin user interface. It is not declared in the Mks UI of the H43 screen.
![image](https://user-images.githubusercontent.com/24864147/115762197-7e5db800-a3a3-11eb-8b4f-215f1e6cdb27.png)

### Steps to Reproduce

1. [First Step]  
The latest Marlin fork of MKS.
2. [Second Step] 
board robin_nano_v2
3. [and so on...] 
Last version VSC+PlateFormIO
env: mks_robin_nano35_stm32

**Expected behavior:** [What you expect to happen]
That the function is integrated in the UI in order to have a request to deploy or store the probe on the screen.

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ghost** [comment]
> ### Description
> The "PAUSE_BEFORE_DEPLOY_STOW" function is not supported by the H43 interface and fails to compile.
> This function is necessary for people who use removable probes like Delta printers.
> 
> At compile time, I have a failure on the feedback screen because the status asks for a Marlin user interface. It is not declared in the Mks UI of the H43 screen.
> ![image](https://user-images.githubusercontent.com/24864147/115762197-7e5db800-a3a3-11eb-8b4f-215f1e6cdb27.png)
> 
> ### Steps to Reproduce
> 1. [First Step]
>    The latest Marlin fork of MKS.
> 2. [Second Step]
>    board robin_nano_v2
> 3. [and so on...]
>    Last version VSC+PlateFormIO
>    env: mks_robin_nano35_stm32
> 
> **Expected behavior:** [What you expect to happen]
> That the function is integrated in the UI in order to have a request to deploy or store the probe on the screen.
> 
> **Actual behavior:** [What actually happens]
> 
> #### Additional Information
> * Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
> * Provide pictures or links to videos that clearly demonstrate the issue.
> * See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

![image](https://user-images.githubusercontent.com/42537573/117600409-6f864c00-b17e-11eb-8856-a4c3533df390.png)

For the error report, I have tested that the function can be compiled normally. From your error information, please confirm whether ts35 and lvgl are closed

**Comment by Foxies-CSTL** [comment]
Hi, 
It's good with the latest fusion Marlin (BUMP 2021-05-14) but I can't run a Delta calibration. Also, I still have problems with fluctuating temperatures in the display (multiple digits) #2143 [https://github.com/MarlinFirmware/Marlin/issues/21603] . There are still two extruders displayed and I can't launch a UBL leveling.
See you later...
Note: I use only H43 port 1 with only #define SERIAL_PORT 3 on the UART Wifi (PA9/PA9)
